### ISSUE TITLE
ps-autoenv and pipenv blocking

### ISSUE THREAD

**Issue by autodataming** [nickcox/ps-autoenv#1]
PS> Import-Module ps-autoenv
PS> echo "echo 'whoa'" > project/.autoenv
PS> cd project
whoa

the above commands are working well;
the following commands didn't work well.
PS> Import-Module ps-autoenv
PS> echo "pipenv shell" > project/.autoenv
PS> cd project

it's blocking.

**Comment by nickcox** [comment]
`ps-autoenv` does, intentionally, block whilst waiting for the given command(s) to finish; I never really expected anyone to run anything interactive.

Not sure how to handle `pipenv shell` off the top of my head... perhaps you could just use the virtualenv 'activate' script?

```sh
# .autoenv
pipenv --venv | Join-Path -ChildPath 'scripts/activate.ps1' | iex

#.autoenv.leave
deactivate
```

**Comment by nickcox** [comment]
Does that help at all? Feel free to reopen if it doesn't or if you have any follow up questions.
